version: '3.8'

services:
  node:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pocs
    volumes:
      - substrate-data:/pocs
    ports:
      - "9944:9944" # Maps WebSockets port
      - "9933:9933" # Maps RPC port
      - "30333:30333" # Maps P2P port
    restart: unless-stopped
    command: ["./target/release/pocs", "--dev", "--rpc-external", "--rpc-cors=Unsafe"]
volumes:
  substrate-data:
