name: Build Ink! Contracts

on:
  push:
    branches: ["master"]
    paths:
      - 'ink-contracts/**'
  pull_request:
    branches: ["master"]
    paths:
      - 'ink-contracts/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ink:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Navigate to the ink-contracts directory
      - name: Change to ink-contracts Directory
        working-directory: ink-contracts
        run: pwd

      # Install Stable Rust Toolchain
      - name: Install Stable Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
          override: true

      # Install Nightly Rust Toolchain with rust-src
      - name: Install Nightly Rust Toolchain (with rust-src)
        working-directory: ink-contracts
        run: |
          rustup install nightly
          rustup component add rust-src --toolchain nightly
          rustup default nightly

      # Add WebAssembly Target
      - name: Add WebAssembly Target
        working-directory: ink-contracts
        run: rustup target add wasm32-unknown-unknown --toolchain nightly

      # Install cargo-contract
      - name: Install cargo-contract
        working-directory: ink-contracts
        run: cargo install cargo-contract --force --locked

      # Build All Ink! Contracts
      - name: Build All Ink! Contracts
        working-directory: ink-contracts
        run: |
          for dir in */; do
            if [ -f "$dir/Cargo.toml" ]; then
              echo "Building contract in $dir"
              (cd "$dir" && cargo contract build)
            fi
          done
