name: Build Ink! Contracts

on:
  push:
    branches: ["master"]
    paths:
      - 'ink-contracts/**'
  pull_request:
    branches: ["master"]
    paths:
      - 'ink-contracts/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ink:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Stable Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Install Nightly Rust Toolchain
        run: rustup install nightly && rustup default nightly

      - name: Add WebAssembly Target
        run: rustup target add wasm32-unknown-unknown --toolchain nightly

      - name: Install cargo-contract
        run: cargo install cargo-contract --force --locked
      
      - name: Build All Ink! Contracts
        run: |
          for dir in ink-contracts/*/; do
            if [ -f "$dir/Cargo.toml" ]; then
              echo "Building contract in $dir"
              (cd "$dir" && cargo contract build)
            fi
          done
