name: Build Ink! Contracts

on:
  push:
    branches: ["master"]
    paths:
      - 'ink-contracts/**'
  pull_request:
    branches: ["master"]
    paths:
      - 'ink-contracts/**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Navigate to solo-substrate-chain
      - name: Change to ink-contracts Directory
        working-directory: ink-contracts
        run: pwd

      # Install system dependencies
      - name: Install Dependencies
        working-directory: ink-contracts
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
          build-essential \
          clang \
          curl \
          libssl-dev \
          protobuf-compiler

      # Install Rust and set up environment
      - name: Install Rust
        working-directory: ink-contracts
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      # Set Rust stable as the default and update toolchains
      - name: Set Rust Stable and Update
        working-directory: ink-contracts
        run: |
          rustup default stable
          rustup update

      # Install Rust nightly version (2023-12-21) and wasm target
      - name: Install Rust Nightly and wasm32 Target
        working-directory: ink-contracts
        run: |
          rustup install nightly
          rustup target add wasm32-unknown-unknown --toolchain nightly

      # Install cargo-contract
      - name: Install cargo-contract
        working-directory: ink-contracts
        run: |
          rustup component add rust-src
          cargo install --force --locked cargo-contract

      # Build All Ink! Contracts (Force Nightly Toolchain)
      - name: Build All Ink! Contracts
        working-directory: ink-contracts
        run: |
          for dir in */; do
            if [ -f "$dir/Cargo.toml" ]; then
              echo "Building contract in $dir"
              (cd "$dir" && cargo contract build)
            fi
          done
