name: RustDocs

on:
  push:
    branches: ["ci/cd"]


jobs:
  build:
    runs-on: macos-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2023-12-21
        components: rustfmt, rustc-dev, rust-docs
        override: true

    - name: Install Protocol Buffers Compiler
      run: brew install protobuf

    - name: Set PROTOC Environment Variable
      run: echo "PROTOC=$(which protoc)" >> $GITHUB_ENV

    - name: Install wasm32-unknown-unknown target
      run: rustup target add wasm32-unknown-unknown

    - name: Generate docs
      run: |
        cd solo-substrate-chain
        cargo doc -p pallet-contracts --no-deps --document-private-items

    - name: Ensure target/doc exists
      run: |
        if [ ! -d "solo-substrate-chain/target/doc" ]; then
          echo "Documentation was not generated!"
          exit 1
        fi

    - name: Copy documentation files to root
      run: cp -R solo-substrate-chain/target/doc .

    - name: Create index.html file
      run: echo '<meta http-equiv="refresh" content="0;url=target/doc/pallet_contracts/index.html">' > index.html

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        
        if ! git show-ref --verify --quiet refs/heads/gh-pages; then
          git checkout --orphan gh-pages
        else
          git checkout gh-pages
        fi
        
        git rm -rf . || true
        cp -R target/doc ./
        cp index.html ./
        git add .
        
        git commit -m "Update documentation" || echo "No changes to commit"
        git push -f origin gh-pages
