name: RustDocs

on:
  push:
    branches: ["ci/cd"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        # Checkout the repository
        - name: Checkout Repository
          uses: actions/checkout@v3
  
        # Navigate to solo-substrate-chain
        - name: Change to solo-substrate-chain
          working-directory: solo-substrate-chain
          run: pwd
  
        # Install system dependencies
        - name: Install Dependencies
          working-directory: solo-substrate-chain
          run: |
            sudo apt-get update && \
            sudo apt-get install -y \
            build-essential \
            clang \
            curl \
            libssl-dev \
            protobuf-compiler
  
        # Install Rust and set up environment
        - name: Install Rust
          working-directory: solo-substrate-chain
          run: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            echo "$HOME/.cargo/bin" >> $GITHUB_PATH
  
        # Set Rust stable as the default and update toolchains
        - name: Set Rust Stable and Update
          working-directory: solo-substrate-chain
          run: |
            rustup default stable
            rustup update
  
        # Install Rust nightly version (2023-12-21) and wasm target
        - name: Install Rust Nightly and wasm32 Target
          working-directory: solo-substrate-chain
          run: |
            rustup install nightly-2023-12-21
            rustup target add wasm32-unknown-unknown --toolchain nightly-2023-12-21
  
        # Set project to use Rust nightly-2023-12-21
        - name: Override to Nightly
          working-directory: solo-substrate-chain
          run: rustup override set nightly-2023-12-21
  
        # Set additional environment variables
        - name: Set Environment Variables
          working-directory: solo-substrate-chain
          run: |
            echo "PROTOC=$(which protoc)" >> $GITHUB_ENV
            echo "RUSTFLAGS=-C target-cpu=native" >> $GITHUB_ENV
  
        - name: Generate docs
          working-directory: solo-substrate-chain       
          run: cargo doc -p pallet-contracts

        - name: Validate Documentation
          working-directory: solo-substrate-chain
          run: |
            if [ ! -d "target/doc" ]; then
              echo "❌ Documentation was not generated!"
              exit 1
            fi
  
        - name: Copy documentation files to root
          working-directory: solo-substrate-chain       
          run: cp -R target/doc .

        - name: Create index.html file
          run: |
           echo '<meta http-equiv=refresh content=0;url=target/doc/pallet_contracts/index.html>' > index.html
           ls -lh index.html
           
        - name: Stash index.html
          working-directory: solo-substrate-chain
          run: git stash --include-untracked
         
        - name: Deploy to GitHub Pages
          working-directory: solo-substrate-chain
          run: |
             git fetch origin gh-pages
             git checkout --orphan gh-pages
             git rm -rf .
             git stash pop
             git add -f target/doc index.html
             git commit -m "Update documentation"
             git push -f origin gh-pages